# Synthwave Charm — P10k color overlay
# Sourced after ~/.p10k.zsh to override segment colors.
# Re-source with: source ~/.p10k.zsh && source <this-file>

# Suppress instant prompt warnings from noisy init scripts (e.g. gcloud)
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# ── Prompt frame ──
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%F{#6E63FF}╭─%f'
typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%F{#6E63FF}├─%f'
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{#6E63FF}╰─%f'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND='#43366E'

# ── OS icon ──
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#8B3DFF'
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#F8F7FF'

# ── Directory ──
typeset -g POWERLEVEL9K_DIR_BACKGROUND='#4F61FF'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#F8F7FF'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#D6DBFF'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#FFFFFF'

# ── VCS (git) ──
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#2EF2A3'
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#FFC93C'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#C46BFF'
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND='#FF6B7A'
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND='#322655'

# ── Status ──
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#2EF2A3'
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND='#1A1333'
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND='#2EF2A3'
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND='#1A1333'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#0E0A1F'
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND='#FF6B7A'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND='#0E0A1F'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND='#FF6B7A'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND='#0E0A1F'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND='#FF6B7A'

# ── Command execution time ──
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#0E0A1F'
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='#FF9F1C'

# ── Background jobs ──
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='#D59BFF'
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='#1A1333'

# ── Direnv ──
typeset -g POWERLEVEL9K_DIRENV_FOREGROUND='#FFC93C'
typeset -g POWERLEVEL9K_DIRENV_BACKGROUND='#1A1333'

# ── Kubernetes context ──
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND='#0E0A1F'
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND='#21E6FF'

# ── AWS ──
typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND='#0E0A1F'
typeset -g POWERLEVEL9K_AWS_DEFAULT_BACKGROUND='#FF9F1C'

# ── Time ──
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#0E0A1F'
typeset -g POWERLEVEL9K_TIME_BACKGROUND='#C46BFF'

# ── Prompt char (on line 2) ──
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#2EF2A3'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#FF6B7A'

# ── Language versions (right prompt) ──
typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND='#0E0A1F'
typeset -g POWERLEVEL9K_GO_VERSION_BACKGROUND='#21E6FF'
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND='#0E0A1F'
typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND='#2EF2A3'
typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND='#0E0A1F'
typeset -g POWERLEVEL9K_RUST_VERSION_BACKGROUND='#FF9F1C'
typeset -g POWERLEVEL9K_PYTHON_VERSION_FOREGROUND='#0E0A1F'
typeset -g POWERLEVEL9K_PYTHON_VERSION_BACKGROUND='#FFC93C'

# ── Azure / GCloud ──
typeset -g POWERLEVEL9K_AZURE_FOREGROUND='#F8F7FF'
typeset -g POWERLEVEL9K_AZURE_BACKGROUND='#5A6BFF'
typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND='#F8F7FF'
typeset -g POWERLEVEL9K_GCLOUD_BACKGROUND='#5A6BFF'

# ── Terraform ──
typeset -g POWERLEVEL9K_TERRAFORM_OTHER_FOREGROUND='#D59BFF'
typeset -g POWERLEVEL9K_TERRAFORM_OTHER_BACKGROUND='#1A1333'
typeset -g POWERLEVEL9K_TERRAFORM_VERSION_FOREGROUND='#D59BFF'
typeset -g POWERLEVEL9K_TERRAFORM_VERSION_BACKGROUND='#1A1333'

# ── Context (user@host) ──
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND='#F8F7FF'
typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND='#322655'
